version: '3'

services:
  rabbitmq3:
    container_name: message-broker
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret'
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '5672:5672'
      - '15672:15672'