version: '3.9'

services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - smartRanking
    ports:
      - '5672:5672'
      - '15672:15672'
  
  api-gateway:
    container_name: 'api-gateway'
    command: sh -c 'yarn && yarn start:dev'
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always

    environment:
      AMQP_URL: ${AMQP_URL}
      AMQP_QUEUE_ADMIN: ${AMQP_QUEUE_ADMIN}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_SECURE: ${CLOUDINARY_SECURE}
      
      NODE_ENV: ${NODE_ENV}

    ports:
      - '3333:3333'
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - smartRanking
    volumes:
      - ./gateway/.:/usr/app/gateway
      - /user/app/gateway/node_modules
  
  admin-service:
    container_name: 'admin-service'
    command: sh -c 'yarn && yarn start:dev'
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    restart: always

    environment:
      AMQP_URL: ${AMQP_URL}
      AMQP_QUEUE_ADMIN: ${AMQP_QUEUE_ADMIN}

      NODE_ENV: ${NODE_ENV}
      MONGOOSE_URI: ${MONGOOSE_URI}

    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - smartRanking
    volumes:
      - ./admin-service/.:/usr/app/admin-service
      - /user/app/admin-service/node_modules

networks:
  smartRanking:
    driver: 'bridge'